services:
  psql:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - psql
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_USER}@admin.com
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5050:80"
    restart: always
